# Generated by Django 4.0 on 2022-01-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vialpi', '0002_contactus'),
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to='vialpi.user'),
        ),
    ]
