# Generated by Django 4.0 on 2022-01-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vialpi', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
