# Generated by Django 4.0 on 2022-01-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vialpi', '0003_alter_contactus_phone_number_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
